import { SpotifyAudioFeatures, AudioFeatures } from '../types/spotify'

export const adaptAudioFeatures = ({
  id,
  track_href,
  danceability,
  acousticness,
  instrumentalness,
  speechiness,
  liveness,
  loudness,
  energy,
  tempo,
  mode,
  key,
  valence,
}: SpotifyAudioFeatures): AudioFeatures => ({
  id,
  trackHref: track_href,
  danceability,
  acousticness,
  instrumentalness,
  speechiness,
  liveness,
  loudness,
  energy,
  tempo,
  mode,
  key,
  valence,
})
