services:
  statistics:
    build:
      context: .
      dockerfile: ./apps/statistics/Dockerfile
      target: development
    command: yarn start:dev statistics
    env_file:
      - ./apps/statistics/.env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - ./usr/src/app:/node_modules
    ports:
      - 4000:4000

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - ./usr/src/app:/node_modules
    ports:
      - 4001:4001

  player:
    build:
      context: .
      dockerfile: ./apps/player/Dockerfile
      target: development
    command: yarn start:dev player
    env_file:
      - ./apps/player/.env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - ./usr/src/app:/node_modules
    ports:
      - 4002:4002

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
