version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: pnpm run start:dev
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/app/src
      - /usr/app/src/node_modules
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  redis:
    image: bitnami/redis:7.4
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
