services:
  - type: web
    name: rigtch-music-statistics
    env: docker
    dockerfilePath: ./apps/statistics/Dockerfile
    pullRequestPreviewsEnabled: true
    buildFilter:
      ignoredPaths:
        - apps/player
        - apps/auth
    envVars:
      - key: NODE_ENV
        value: production
        previewValue: development

  - type: web
    name: rigtch-music-auth
    env: docker
    dockerfilePath: ./apps/auth/Dockerfile
    pullRequestPreviewsEnabled: true
    buildFilter:
      ignoredPaths:
        - apps/player
        - apps/statistics
    envVars:
      - key: NODE_ENV
        value: production
        previewValue: development
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: rigtch-music-player
    env: docker
    dockerfilePath: ./apps/player/Dockerfile
    pullRequestPreviewsEnabled: true
    buildFilter:
      ignoredPaths:
        - apps/statistics
        - apps/auth
    envVars:
      - key: NODE_ENV
        value: production
        previewValue: development
