export enum Environment {
  PORT = 'PORT',
  SPOTIFY_CLIENT_ID = 'SPOTIFY_CLIENT_ID',
  SPOTIFY_CLIENT_SECRET = 'SPOTIFY_CLIENT_SECRET',
  SPOTIFY_CALLBACK_URL = 'SPOTIFY_CALLBACK_URL',
  SPOTIFY_BASE_URL = 'SPOTIFY_BASE_URL',
  SPOTIFY_ACCOUNTS_URL = 'SPOTIFY_ACCOUNTS_URL',
  JWT_SECRET = 'JWT_SECRET',
  NODE_ENV = 'NODE_ENV',
}
